{
 "title": "Apple Health Sleep Data",
 "time": { "from": "now-4M", "to": "now" },
 "panels": [
  {
   "title": "Weight changes chart",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"date\" AS time,\n  weight_kg\nFROM personal_data.weights\nWHERE \nuser_id = 1\nORDER BY \"date\"\n"
    }
   ]
  },
  {
   "title": "Apple Watch - Total Sleep Time (mins)",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "rawSql": "SELECT \n  DATE(start_date) AS day,\n  ROUND(SUM(duration_minutes), 1) AS total_sleep_minutes\nFROM sleep_data\n \nWHERE $__timeFilter(start_date) \nAND source_name = 'Anastasiia’s Apple Watch'\nAND \nsleep_type  in (\n'HKCategoryValueSleepAnalysisAsleepCore', 'HKCategoryValueSleepAnalysisAsleepDeep', 'HKCategoryValueSleepAnalysisAsleepREM', 'HKCategoryValueSleepAnalysisAsleepUnspecified'\n)\nGROUP BY day\nORDER BY day;\n\n"
    }
   ]
  },
  {
   "title": "Avg Total Sleep Time ",
   "type": "stat",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\nSELECT avg(total_sleep_minutes) FROM (\n\nSELECT \n  DATE(start_date) AS day,\n  ROUND(SUM(duration_minutes), 1) AS total_sleep_minutes\nFROM sleep_data\n \nWHERE $__timeFilter(start_date) \nAND source_name = 'Anastasiia’s Apple Watch'\nAND \nsleep_type  in (\n'HKCategoryValueSleepAnalysisAsleepCore', 'HKCategoryValueSleepAnalysisAsleepDeep', 'HKCategoryValueSleepAnalysisAsleepREM', 'HKCategoryValueSleepAnalysisAsleepUnspecified'\n)\nGROUP BY day\nORDER BY day\n\n)\n\nwhere total_sleep_minutes > 150"
    }
   ]
  }
 ]
}