{
 "title": "Fatsecrets Dashboard Stats",
 "time": { "from": "2021-04-07T00:00:00.000Z", "to": "2025-05-16T00:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "user",
    "query": "SELECT DISTINCT u.fatsecret_user_id AS __text, u.id AS __value\nFROM personal_data.users u\nJOIN personal_data.weights w ON w.user_id = u.id\nORDER BY u.fatsecret_user_id;\n"
   }
  ]
 },
 "panels": [
  { "title": "Time-based", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Weight changes chart",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"date\" AS time,\n  weight_kg\nFROM personal_data.weights\nWHERE \nuser_id = ${user}\nORDER BY \"date\"\n"
    }
   ]
  },
  {
   "title": "Aggregation interval",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "rawSql": "SELECT\n\t count(date)\n\tFROM (\n\t  SELECT\n\t    date\n\t\t\tFROM personal_data.food_entries\n\t\tWHERE $__timeFilter(date) AND user_id = ${user} \n\t  GROUP BY date\n\t) "
    }
   ]
  },
  {
   "title": "Weight changes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"date\" AS time,\n  weight_kg\nFROM personal_data.weights\nWHERE $__timeFilter(date) AND user_id = ${user} \nORDER BY \"date\"\n"
    }
   ]
  },
  {
   "title": "Estimated weight loss (Calorie Balance / 9000)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select SUM( W / 9) AS \"Estimated weight loss\"  from (\n\tSELECT\n\t  f.date,\n\t\tf.total_calories - e.total_calories  as W\n\t -- COALESCE(f.total_calories, 0) - COALESCE(e.total_calories, 0)  as W\n\tFROM (\n\t  SELECT\n\t    date,\n\t    SUM(Calories) AS total_calories\n\t  FROM personal_data.food_entries\n\t\tWHERE $__timeFilter(date) AND user_id = ${user} \n\t  GROUP BY date\n\t) f\n\tFULL OUTER JOIN (\n\t  SELECT\n\t    date,\n\t    SUM(Calories) AS total_calories\n\t  FROM personal_data.exercise_entries\n\t\tWHERE $__timeFilter(date) AND user_id = ${user} \n\t  GROUP BY date\n\t) e\n\tON f.date = e.date\n\tORDER BY f.date\n)\n"
    }
   ]
  },
  {
   "title": "Calories Consumed / Calories Burned",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS time,\n  SUM(calories) AS \"Calories Consumed\"\nFROM personal_data.food_entries\nWHERE $__timeFilter(date) and user_id = ${user}\nGROUP BY date\nORDER BY date\n"
    },
    {
     "rawSql": "SELECT\n  date AS time,\n  SUM(calories) AS \"Calories Burned\"\nFROM personal_data.exercise_entries\nWHERE $__timeFilter(date) and user_id = ${user}\nGROUP BY date\nORDER BY date\n"
    }
   ]
  },
  {
   "title": "Total Calories Consumed per meal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS time,\n  SUM(calories) AS \"Breakfast\"\nFROM personal_data.food_entries\nWHERE $__timeFilter(date) and user_id = ${user} and meal_type = 'Breakfast'\nGROUP BY date\nORDER BY date\n"
    },
    {
     "rawSql": "SELECT\n  date AS time,\n  SUM(calories) AS \"Lunch\"\nFROM personal_data.food_entries\nWHERE $__timeFilter(date) and user_id = ${user} and meal_type = 'Lunch'\nGROUP BY date\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS time,\n  SUM(calories) AS \"Dinner\"\nFROM personal_data.food_entries\nWHERE $__timeFilter(date) and user_id = ${user} and meal_type = 'Dinner'\nGROUP BY date\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS time,\n  SUM(calories) AS \"Snacks\"\nFROM personal_data.food_entries\nWHERE $__timeFilter(date) and user_id = ${user} and meal_type = 'Other'\nGROUP BY date\nORDER BY date"
    }
   ]
  },
  {
   "title": "Total Calories Consumed per meal",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  meal_type, \n  AVG(calories) AS \"Calories\" FROM (\n\n            SELECT\n              meal_type, \n              SUM(calories) AS \"calories\"\n            FROM personal_data.food_entries\n            WHERE $__timeFilter(date) and user_id = ${user}\n            GROUP BY meal_type, date\n\n  ) GROUP BY meal_type\n\n\n"
    }
   ]
  },
  {
   "title": "Calories Per Meal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS time,   \n  SUM(calories) AS \"Breakfast\"\nFROM personal_data.food_entries\nWHERE $__timeFilter(date) and user_id = ${user} and meal_type = 'Breakfast'\nGROUP BY date\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS time,\n  SUM(calories) AS \"Lunch\"\nFROM personal_data.food_entries\nWHERE $__timeFilter(date) and user_id = ${user} and meal_type = 'Lunch'\nGROUP BY date\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS time,\n  SUM(calories) AS \"Dinner\"\nFROM personal_data.food_entries\nWHERE $__timeFilter(date) and user_id = ${user} and meal_type = 'Dinner'\nGROUP BY date\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS time,\n  SUM(calories) AS \"Snacks\"\nFROM personal_data.food_entries\nWHERE $__timeFilter(date) and user_id = ${user} and meal_type = 'Other'\nGROUP BY date\nORDER BY date"
    }
   ]
  },
  {
   "title": "Number of meals logged",
   "type": "status-history",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "rawSql": "\nSELECT\ne.time, coalesce(\"meals count\", 0) as \"meals count\"\nFROM (\nSELECT\n  date AS time,\n  count (distinct meal_type) as \"meals count\"\nFROM personal_data.food_entries \nWHERE $__timeFilter(date) and user_id = ${user}\nGROUP BY date\nORDER BY date\n) f\nFULL OUTER JOIN (\n  SELECT\n  date AS time\n  FROM personal_data.exercise_entries ee  \n  WHERE $__timeFilter(date) and   user_id = ${user}\nGROUP BY date\nORDER BY date\n) e\nON f.time = e.time\nORDER BY e.time\n"
    }
   ]
  },
  {
   "title": "Calories Consumed / Calories Burned",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS time,\n  SUM(calories) AS \"Calories Consumed\"\nFROM personal_data.food_entries\nWHERE $__timeFilter(date) and user_id = ${user}\nGROUP BY date\nORDER BY date\n"
    },
    {
     "rawSql": "SELECT\n  date AS time,\n  SUM(calories) AS \"Calories Burned\"\nFROM personal_data.exercise_entries\nWHERE $__timeFilter(date) and user_id = ${user}\nGROUP BY date\nORDER BY date\n"
    }
   ]
  },
  {
   "title": "Calories Balance Per Date",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "rawSql": "WITH consumed AS (\n    SELECT\n        date::date AS time,\n        SUM(calories) AS calories_consumed\n    FROM personal_data.food_entries\n    WHERE $__timeFilter(date) AND user_id = ${user}\n    GROUP BY date\n),\nburned AS (\n    SELECT\n        date::date AS time,\n        SUM(calories) AS calories_burned\n    FROM personal_data.exercise_entries\n    WHERE $__timeFilter(date) AND user_id = ${user}\n    GROUP BY date\n)\n\nSELECT\n    COALESCE(c.time, b.time) AS time,\n    calories_consumed - calories_burned  AS \"Calories Balance\"\n   -- COALESCE(c.calories_consumed, 0) - COALESCE(b.calories_burned, 0) AS \"Calories Balance\"\nFROM consumed c\nFULL OUTER JOIN burned b ON c.time = b.time\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "Calories Consumed / Calories Burned ",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {
     "rawSql": "SELECT\n  TO_CHAR(COALESCE(f.date, e.date), 'YYYY-MM-DD') AS date,\n  COALESCE(f.total_calories, 0) AS \"Consumed\",\n  COALESCE(e.total_calories, 0) AS \"Burned\",\n  f.total_calories - e.total_calories AS \"Balance\"\n  --COALESCE(f.total_calories, 0) - COALESCE(e.total_calories, 0) AS \"Balance\"\nFROM (\n  SELECT\n    date,\n    SUM(Calories) AS total_calories\n  FROM personal_data.food_entries\n  WHERE $__timeFilter(date) AND user_id = ${user}\n  GROUP BY date\n) f\nFULL OUTER JOIN (\n  SELECT\n    date,\n    SUM(Calories) AS total_calories\n  FROM personal_data.exercise_entries\n  WHERE $__timeFilter(date) AND user_id = ${user}\n  GROUP BY date\n) e\nON f.date = e.date\nORDER BY date\n"
    }
   ]
  },
  {
   "title": "Calories average ",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COALESCE(f.date, e.date) AS time,\n  COALESCE(f.total_calories, 0) AS \"Calories Consumed (AVG)\",\n  COALESCE(e.total_calories, 0) AS \"Calories Burned (AVG)\",\n  COALESCE(f.total_calories, 0) - COALESCE(e.total_calories, 0) AS \"Calorie Balance (AVG)\"\nFROM (\n  SELECT\n    date,\n    SUM(Calories) AS total_calories\n  FROM personal_data.food_entries\n  WHERE $__timeFilter(date) AND user_id = ${user} \n  GROUP BY date\n) f\nFULL OUTER JOIN (\n  SELECT\n    date,\n    SUM(Calories) AS total_calories\n  FROM personal_data.exercise_entries\n  WHERE $__timeFilter(date) AND user_id = ${user} \n  GROUP BY date\n) e\nON f.date = e.date\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "Calories total",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COALESCE(f.date, e.date) AS time,\n  COALESCE(f.total_calories, 0) AS \"Calories Consumed (Total)\",\n  COALESCE(e.total_calories, 0) AS \"Calories Burned (Total)\",\n  COALESCE(f.total_calories, 0) - COALESCE(e.total_calories, 0) AS \"Calorie Balance (Total)\"\nFROM (\n  SELECT\n    date,\n    SUM(Calories) AS total_calories\n  FROM personal_data.food_entries\n  WHERE $__timeFilter(date) AND user_id = ${user} \n  GROUP BY date\n) f\nFULL OUTER JOIN (\n  SELECT\n    date,\n    SUM(Calories) AS total_calories\n  FROM personal_data.exercise_entries\n  WHERE $__timeFilter(date) AND user_id = ${user} \n  GROUP BY date\n) e\nON f.date = e.date\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "Fats/Carbs/Proteins daily intake",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS time,\n  SUM(fat) AS \"Fats\",\n  SUM(carbohydrate) AS \"Carbs\",\n  SUM(protein) AS \"Proteins\"\nFROM personal_data.food_entries\nWHERE $__timeFilter(date) and user_id = ${user}\nGROUP BY date\nORDER BY date\n"
    }
   ]
  },
  {
   "title": "Fats/Carbs/Proteins daily total intake",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT  \n  ROUND((SUM(fat) * 9) * 100.0 / NULLIF((SUM(fat) * 9 + SUM(carbohydrate) * 4 + SUM(protein) * 4), 0), 1) AS fats,\n  ROUND((SUM(carbohydrate) * 4) * 100.0 / NULLIF((SUM(fat) * 9 + SUM(carbohydrate) * 4 + SUM(protein) * 4), 0), 1) AS carbs,\n  ROUND((SUM(protein) * 4) * 100.0 / NULLIF((SUM(fat) * 9 + SUM(carbohydrate) * 4 + SUM(protein) * 4), 0), 1) AS proteins    \nFROM\n  personal_data.food_entries f\nWHERE $__timeFilter(date) and user_id = ${user};\n"
    }
   ]
  },
  {
   "title": "Fats/Carbs/Proteins daily average intake",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS time,\n  SUM(fat) AS \"Fats\",\n  SUM(carbohydrate) AS \"Carbs\",\n  SUM(protein) AS \"Proteins\",\n  SUM(fiber) AS \"Fibers\"\n\nFROM personal_data.food_entries\nWHERE $__timeFilter(date) and user_id = ${user}\nGROUP BY date\nORDER BY date\n"
    }
   ]
  },
  {
   "title": "Fats/Carbs/Proteins daily total intake",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  TO_CHAR(date, 'YYYY-MM-DD') AS date,\n  SUM(fat) AS \"Fats, g\",\n  SUM(carbohydrate) AS \"Carbs, g\",\n  SUM(protein) AS \"Proteins, g\",\n  SUM(fiber) AS \"Fibers, g\"\n\nFROM personal_data.food_entries\nWHERE $__timeFilter(date) and user_id = ${user}\nGROUP BY date\nORDER BY date desc\n"
    }
   ]
  },
  {
   "title": "Top food eaten",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 131 },
   "targets": [
    {
     "rawSql": "select food_name , count(*)  from personal_data.food_entries \nWHERE $__timeFilter(date) and user_id = ${user}\ngroup by fatsecret_food_id, food_name  \norder by 2 desc limit 20;"
    }
   ]
  }
 ]
}