{
 "title": "Fatsecrets Daily view",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "user",
    "query": "SELECT DISTINCT u.fatsecret_user_id AS __text, u.id AS __value\nFROM personal_data.users u\nJOIN personal_data.weights w ON w.user_id = u.id\nORDER BY u.fatsecret_user_id;\n"
   },
   {
    "name": "days",
    "query": "SELECT \n  date AS __value,\n  CASE\n    WHEN date = CURRENT_DATE THEN 'Today, ' || TO_CHAR(date, 'YYYY-MM-DD')\n    WHEN date = CURRENT_DATE - INTERVAL '1 day' THEN 'Yesterday, ' || TO_CHAR(date, 'YYYY-MM-DD')\n    WHEN date >= CURRENT_DATE - INTERVAL '14 days'\n         AND date < CURRENT_DATE - INTERVAL '7 days'\n         AND EXTRACT(DOW FROM date) = EXTRACT(DOW FROM CURRENT_DATE)\n         THEN 'Last ' || TO_CHAR(date, 'FMDay') || ', ' || TO_CHAR(date, 'YYYY-MM-DD')\n    WHEN date >= CURRENT_DATE - INTERVAL '14 days'\n         AND date < CURRENT_DATE - INTERVAL '7 days'\n         THEN 'Last ' || TO_CHAR(date, 'FMDay') || ', ' || TO_CHAR(date, 'YYYY-MM-DD')\n    ELSE TO_CHAR(date, 'FMDay, YYYY-MM-DD')\n  END AS __text\nFROM personal_data.food_entries\nWHERE date >= CURRENT_DATE - INTERVAL '14 days'\nGROUP BY date\nORDER BY date DESC;\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Daily View (Controlled by 'days' variable)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Hours Ago",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "rawSql": "SELECT\n (EXTRACT(EPOCH FROM now()) - EXTRACT(EPOCH FROM MAX(f.date))) / 3600 as \"Food tracking\",\n (EXTRACT(EPOCH FROM now()) - EXTRACT(EPOCH FROM MAX(e.date))) / 3600 as \"Excersise tracking\"\nFROM personal_data.food_entries f, personal_data.exercise_entries  e\nWHERE f.user_id = ${user} and e.user_id = ${user} \nAND f.date NOT IN (SELECT date FROM personal_data.date_exclusions WHERE user_id = ${user})\nAND e.date NOT IN (SELECT date FROM personal_data.date_exclusions WHERE user_id = ${user});"
    }
   ]
  },
  {
   "title": "Current weight",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  w.\"date\" AS time,\n  w.weight_kg\n  --, w.user_id\n  --u.fatsecret_user_id\nFROM personal_data.weights w\n--JOIN personal_data.users u ON w.user_id = u.id\nWHERE w.user_id = ${user}\nAND w.date NOT IN (SELECT date FROM personal_data.date_exclusions WHERE user_id = ${user})\nORDER BY w.\"date\" DESC\nLIMIT 1;\n"
    }
   ]
  },
  {
   "title": "Latest Date Logged",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "targets": [
    {
     "rawSql": "SELECT\nTO_CHAR(MAX(f.date) , 'YYYY-MM-DD') AS \"Food tracking\",\nTO_CHAR(MAX(e.date) , 'YYYY-MM-DD') AS \"Exercise tracking\"\nFROM personal_data.food_entries f, personal_data.exercise_entries   e\nWHERE f.user_id = ${user} and e.user_id = ${user} \nAND f.date NOT IN (SELECT date FROM personal_data.date_exclusions WHERE user_id = ${user})\nAND e.date NOT IN (SELECT date FROM personal_data.date_exclusions WHERE user_id = ${user})\n-- and f.calories != 0 and e.calories != 0\n"
    }
   ]
  },
  {
   "title": "Calorie Balance",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COALESCE(f.date, e.date) AS time,\n  COALESCE(f.total_calories, 0) AS \"Calories Consumed\",\n  COALESCE(e.total_calories, 0) AS \"Calories Burned\",\n  COALESCE(f.total_calories, 0) - COALESCE(e.total_calories, 0) AS \"Calorie Balance\"\nFROM (\n  SELECT\n    date,\n    SUM(Calories) AS total_calories\n  FROM personal_data.food_entries\n  WHERE date = TO_TIMESTAMP(${days} / 1000)::date AND user_id = ${user} \n  AND date NOT IN (SELECT date FROM personal_data.date_exclusions WHERE user_id = ${user})\n  GROUP BY date\n) f\nFULL OUTER JOIN (\n  SELECT\n    date,\n    SUM(Calories) AS total_calories\n  FROM personal_data.exercise_entries\n  WHERE date = TO_TIMESTAMP(${days} / 1000)::date AND user_id = ${user} \n  AND date NOT IN (SELECT date FROM personal_data.date_exclusions WHERE user_id = ${user})\n  GROUP BY date\n) e\nON f.date = e.date\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "Fats/Carbs/Proteins daily total intake",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT  \n  ROUND((SUM(fat) * 9) * 100.0 / NULLIF((SUM(fat) * 9 + SUM(carbohydrate) * 4 + SUM(protein) * 4), 0), 1) AS fats,\n  ROUND((SUM(carbohydrate) * 4) * 100.0 / NULLIF((SUM(fat) * 9 + SUM(carbohydrate) * 4 + SUM(protein) * 4), 0), 1) AS carbs,\n  ROUND((SUM(protein) * 4) * 100.0 / NULLIF((SUM(fat) * 9 + SUM(carbohydrate) * 4 + SUM(protein) * 4), 0), 1) AS proteins    \nFROM\n  personal_data.food_entries f\nWHERE\n  user_id = ${user}\n  AND date = TO_TIMESTAMP(${days} / 1000) :: date\n  AND date NOT IN (SELECT date FROM personal_data.date_exclusions WHERE user_id = ${user})\n;\n"
    }
   ]
  },
  {
   "title": "Fats/Carbs/Proteins daily total intake",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS time,\n  SUM(fat) AS \"Fats\",\n  SUM(carbohydrate) AS \"Carbs\",\n  SUM(protein) AS \"Proteins\",\n  SUM(fiber) AS \"Fibers\"\n\nFROM personal_data.food_entries\nWHERE user_id = ${user} and date = TO_TIMESTAMP(${days} / 1000)::date AND user_id = ${user} \nAND date NOT IN (SELECT date FROM personal_data.date_exclusions WHERE user_id = ${user})\nGROUP BY date\nORDER BY date DESC LIMIT  1\n"
    }
   ]
  },
  {
   "title": "Calories per meal",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select meal_type, sum(calories) from personal_data.food_entries f\nWHERE user_id = ${user} and date = TO_TIMESTAMP(${days} / 1000)::date AND user_id = ${user} \nAND date NOT IN (SELECT date FROM personal_data.date_exclusions WHERE user_id = ${user})\ngroup by meal_type \norder by 2 desc\n"
    }
   ]
  },
  {
   "title": "Number of meals logged",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\nSELECT\ne.time, coalesce(\"meals count\", 0) as \"Meals logged\"\nFROM (\nSELECT\n  date AS time,\n  count (distinct meal_type) as \"meals count\"\nFROM personal_data.food_entries \nWHERE user_id = ${user} and date = TO_TIMESTAMP(${days} / 1000)::date AND user_id = ${user} \nAND date NOT IN (SELECT date FROM personal_data.date_exclusions WHERE user_id = ${user})\nGROUP BY date\nORDER BY date\n) f\nFULL OUTER JOIN (\n  SELECT\n  date AS time\n  FROM personal_data.exercise_entries ee  \nWHERE user_id = ${user} and date = TO_TIMESTAMP(${days} / 1000)::date AND user_id = ${user} \nAND date NOT IN (SELECT date FROM personal_data.date_exclusions WHERE user_id = ${user})\nGROUP BY date\nORDER BY date\n) e\nON f.time = e.time\nORDER BY e.time\n"
    }
   ]
  },
  {
   "title": "Breakfast",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT\n  --date AS time,\n  food_name,\n  calories,\n  fat,\n  carbohydrate,\n  protein,\n  fiber\nFROM\n  personal_data.food_entries f\nWHERE\n  user_id = ${user}\n  and date = TO_TIMESTAMP(${days} / 1000) :: date\n  AND user_id = ${user}\n  AND date NOT IN (SELECT date FROM personal_data.date_exclusions WHERE user_id = ${user})\n  and meal_type = 'Breakfast'"
    }
   ]
  },
  {
   "title": "Fats/Carbs/Proteins for Breakfast",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT  \n  ROUND((SUM(fat) * 9) * 100.0 / NULLIF((SUM(fat) * 9 + SUM(carbohydrate) * 4 + SUM(protein) * 4), 0), 1) AS fats,\n  ROUND((SUM(carbohydrate) * 4) * 100.0 / NULLIF((SUM(fat) * 9 + SUM(carbohydrate) * 4 + SUM(protein) * 4), 0), 1) AS carbs,\n  ROUND((SUM(protein) * 4) * 100.0 / NULLIF((SUM(fat) * 9 + SUM(carbohydrate) * 4 + SUM(protein) * 4), 0), 1) AS proteins    \nFROM\n  personal_data.food_entries f\nWHERE\n  user_id = ${user}\n  AND date = TO_TIMESTAMP(${days} / 1000) :: date\n  AND date NOT IN (SELECT date FROM personal_data.date_exclusions WHERE user_id = ${user})\n  AND meal_type = 'Breakfast'\n;\n"
    }
   ]
  },
  {
   "title": "Dinner",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "rawSql": "SELECT\n  --date AS time,\n  food_name,\n  calories,\n  fat,\n  carbohydrate,\n  protein,\n  fiber\nFROM\n  personal_data.food_entries f\nWHERE\n  user_id = ${user}\n  and date = TO_TIMESTAMP(${days} / 1000) :: date\n  AND user_id = ${user}\n  AND date NOT IN (SELECT date FROM personal_data.date_exclusions WHERE user_id = ${user})\n  and meal_type = 'Dinner'"
    }
   ]
  },
  {
   "title": "Fats/Carbs/Proteins for Dinner",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT  \n  ROUND((SUM(fat) * 9) * 100.0 / NULLIF((SUM(fat) * 9 + SUM(carbohydrate) * 4 + SUM(protein) * 4), 0), 1) AS fats,\n  ROUND((SUM(carbohydrate) * 4) * 100.0 / NULLIF((SUM(fat) * 9 + SUM(carbohydrate) * 4 + SUM(protein) * 4), 0), 1) AS carbs,\n  ROUND((SUM(protein) * 4) * 100.0 / NULLIF((SUM(fat) * 9 + SUM(carbohydrate) * 4 + SUM(protein) * 4), 0), 1) AS proteins    \nFROM\n  personal_data.food_entries f\nWHERE\n  user_id = ${user}\n  AND date = TO_TIMESTAMP(${days} / 1000) :: date\n  AND date NOT IN (SELECT date FROM personal_data.date_exclusions WHERE user_id = ${user})\n  and meal_type = 'Dinner';\n"
    }
   ]
  },
  {
   "title": "Lunch",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "rawSql": "SELECT\n  --date AS time,\n  food_name,\n  calories,\n  fat,\n  carbohydrate,\n  protein,\n  fiber\n\nFROM personal_data.food_entries\nWHERE user_id = ${user} and date = TO_TIMESTAMP(${days} / 1000)::date AND user_id = ${user} \nAND date NOT IN (SELECT date FROM personal_data.date_exclusions WHERE user_id = ${user})\nand meal_type = 'Lunch'"
    }
   ]
  },
  {
   "title": "Fats/Carbs/Proteins for Lunch",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT  \n  ROUND((SUM(fat) * 9) * 100.0 / NULLIF((SUM(fat) * 9 + SUM(carbohydrate) * 4 + SUM(protein) * 4), 0), 1) AS fats,\n  ROUND((SUM(carbohydrate) * 4) * 100.0 / NULLIF((SUM(fat) * 9 + SUM(carbohydrate) * 4 + SUM(protein) * 4), 0), 1) AS carbs,\n  ROUND((SUM(protein) * 4) * 100.0 / NULLIF((SUM(fat) * 9 + SUM(carbohydrate) * 4 + SUM(protein) * 4), 0), 1) AS proteins    \nFROM\n  personal_data.food_entries f\nWHERE\n  user_id = ${user}\n  AND date = TO_TIMESTAMP(${days} / 1000) :: date\n  AND date NOT IN (SELECT date FROM personal_data.date_exclusions WHERE user_id = ${user})\nand meal_type = 'Lunch';\n"
    }
   ]
  },
  {
   "title": "Snacls / Other",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "rawSql": "SELECT\n  --date AS time,\n  food_name,\n  calories,\n  fat,\n  carbohydrate,\n  protein,\n  fiber\n\nFROM personal_data.food_entries\nWHERE user_id = ${user} and date = TO_TIMESTAMP(${days} / 1000)::date AND user_id = ${user} \nAND date NOT IN (SELECT date FROM personal_data.date_exclusions WHERE user_id = ${user})\nand meal_type = 'Other'"
    }
   ]
  },
  {
   "title": "Fats/Carbs/Proteins for Snacks",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT  \n  ROUND((SUM(fat) * 9) * 100.0 / NULLIF((SUM(fat) * 9 + SUM(carbohydrate) * 4 + SUM(protein) * 4), 0), 1) AS fats,\n  ROUND((SUM(carbohydrate) * 4) * 100.0 / NULLIF((SUM(fat) * 9 + SUM(carbohydrate) * 4 + SUM(protein) * 4), 0), 1) AS carbs,\n  ROUND((SUM(protein) * 4) * 100.0 / NULLIF((SUM(fat) * 9 + SUM(carbohydrate) * 4 + SUM(protein) * 4), 0), 1) AS proteins    \nFROM\n  personal_data.food_entries f\nWHERE\n  user_id = ${user}\n  AND date = TO_TIMESTAMP(${days} / 1000) :: date\n  AND date NOT IN (SELECT date FROM personal_data.date_exclusions WHERE user_id = ${user})\nand meal_type = 'Other';\n"
    }
   ]
  }
 ]
}