{
 "title": "Fatsecrets Estimated Food Nutrients Daily View",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "user",
    "query": "SELECT DISTINCT u.fatsecret_user_id AS __text, u.id AS __value\nFROM personal_data.users u\nJOIN personal_data.weights w ON w.user_id = u.id\nORDER BY u.fatsecret_user_id;\n"
   },
   {
    "name": "days",
    "query": "SELECT \n  date AS __value,\n  CASE\n    WHEN date = CURRENT_DATE THEN 'Today, ' || TO_CHAR(date, 'YYYY-MM-DD')\n    WHEN date = CURRENT_DATE - INTERVAL '1 day' THEN 'Yesterday, ' || TO_CHAR(date, 'YYYY-MM-DD')\n    WHEN date >= CURRENT_DATE - INTERVAL '14 days'\n         AND date < CURRENT_DATE - INTERVAL '7 days'\n         AND EXTRACT(DOW FROM date) = EXTRACT(DOW FROM CURRENT_DATE)\n         THEN 'Last ' || TO_CHAR(date, 'FMDay') || ', ' || TO_CHAR(date, 'YYYY-MM-DD')\n    WHEN date >= CURRENT_DATE - INTERVAL '14 days'\n         AND date < CURRENT_DATE - INTERVAL '7 days'\n         THEN 'Last ' || TO_CHAR(date, 'FMDay') || ', ' || TO_CHAR(date, 'YYYY-MM-DD')\n    ELSE TO_CHAR(date, 'FMDay, YYYY-MM-DD')\n  END AS __text\nFROM personal_data.food_entries\nWHERE date >= CURRENT_DATE - INTERVAL '14 days'\nGROUP BY date\nORDER BY date DESC;\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Requires attention \t⚠️ ",
   "type": "table",
   "gridPos": { "h": 24, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT nutrient_name as \"Nutrient\", intake_value as \"Intake total\", rda_value as \"Reference value\", percent_of_rda as \"RDA, %\", comment as \"Comment\"\nFROM personal_data.daily_micronutrient_summary\nWHERE user_id = ${user} and date = TO_TIMESTAMP(${days} / 1000)::date AND user_id = ${user} \nAND comment in ('Low', 'Fair')\nORDER BY percent_of_rda"
    }
   ]
  },
  {
   "title": "Meets goal \t✅",
   "type": "table",
   "gridPos": { "h": 24, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT nutrient_name as \"Nutrient\", intake_value as \"Intake total\", rda_value as \"Reference value\", percent_of_rda as \"RDA, %\", comment as \"Comment\"\nFROM personal_data.daily_micronutrient_summary\nWHERE user_id = ${user} and date = TO_TIMESTAMP(${days} / 1000)::date AND user_id = ${user} \nAND comment in ('Good', 'Great', 'Excellent', 'High')\nORDER BY percent_of_rda"
    }
   ]
  },
  {
   "title": "RDA, %",
   "type": "barchart",
   "gridPos": { "h": 27, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \n    nutrient_name AS \"Nutrient\", \n    AVG(percent_of_rda) AS \"RDA, %\"\nFROM personal_data.daily_micronutrient_summary\nWHERE \n    user_id = ${user} \n    AND date = TO_TIMESTAMP(${days} / 1000)::date\nGROUP BY nutrient_name\nORDER BY AVG(percent_of_rda);\n"
    }
   ]
  }
 ]
}