{
 "title": "Nutrients Weekly Stats",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "user",
    "query": "SELECT DISTINCT u.fatsecret_user_id AS __text, u.id AS __value\nFROM personal_data.users u\nJOIN personal_data.weights w ON w.user_id = u.id\nORDER BY u.fatsecret_user_id;\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Omega-3 Fatty Acids (mg)",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \n    week_start_date,\n    avg_percent_of_rda || '% (' || weekly_status || ')' AS label\nFROM personal_data.weekly_micronutrient_summary\nWHERE $__timeFilter(week_start_date) \n  AND  user_id = ${user}\n  AND nutrient_name = 'Omega-3 Fatty Acids (mg)'\nORDER BY week_start_date\n"
    }
   ]
  },
  { "title": "Vitamins", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Vitamin A (mcg)",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \n    week_start_date,\n    avg_percent_of_rda || '% (' || weekly_status || ')' AS label\n\nFROM personal_data.weekly_micronutrient_summary\nWHERE $__timeFilter(week_start_date) \n  AND  user_id = ${user}\n  AND nutrient_name = 'Vitamin A (mcg)'\nORDER BY week_start_date\n"
    }
   ]
  },
  {
   "title": "Vitamin C (mg)",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \n    week_start_date,\n    avg_percent_of_rda || '% (' || weekly_status || ')' AS label\n\nFROM personal_data.weekly_micronutrient_summary\nWHERE $__timeFilter(week_start_date) \n  AND  user_id = ${user}\n  AND nutrient_name = 'Vitamin C (mg)'\nORDER BY week_start_date\n"
    }
   ]
  },
  {
   "title": "Vitamin D (mcg)",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \n    week_start_date,\n    avg_percent_of_rda || '% (' || weekly_status || ')' AS label\n\nFROM personal_data.weekly_micronutrient_summary\nWHERE $__timeFilter(week_start_date) \n  AND  user_id = ${user}\n  AND nutrient_name = 'Vitamin D (mcg)'\nORDER BY week_start_date\n"
    }
   ]
  },
  {
   "title": "Vitamin K (mcg)",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \n    week_start_date,\n    avg_percent_of_rda || '% (' || weekly_status || ')' AS label\n\nFROM personal_data.weekly_micronutrient_summary\nWHERE $__timeFilter(week_start_date) \n  AND  user_id = ${user}\n  AND nutrient_name = 'Vitamin K (mcg)'\nORDER BY week_start_date\n"
    }
   ]
  },
  { "title": "Minerals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Ca - Calcium (mg)",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \n    week_start_date,\n    avg_percent_of_rda || '% (' || weekly_status || ')' AS label\n\nFROM personal_data.weekly_micronutrient_summary\nWHERE $__timeFilter(week_start_date) \n  AND  user_id = ${user}\n  AND nutrient_name = 'Calcium (mg)'\nORDER BY week_start_date\n"
    }
   ]
  },
  {
   "title": "Fe - Iron (mg)",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \n    week_start_date,\n    avg_percent_of_rda || '% (' || weekly_status || ')' AS label\n\nFROM personal_data.weekly_micronutrient_summary\nWHERE $__timeFilter(week_start_date) \n  AND  user_id = ${user}\n  AND nutrient_name = 'Iron (mg)'\nORDER BY week_start_date\n"
    }
   ]
  },
  {
   "title": "Mg - Magnesium (mg)",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \n    week_start_date,\n    avg_percent_of_rda || '% (' || weekly_status || ')' AS label\n\nFROM personal_data.weekly_micronutrient_summary\nWHERE $__timeFilter(week_start_date) \n  AND  user_id = ${user}\n  AND nutrient_name = 'Magnesium (mg)'\nORDER BY week_start_date\n"
    }
   ]
  },
  {
   "title": "K - Potassium (mg)",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \n    week_start_date,\n    avg_percent_of_rda || '% (' || weekly_status || ')' AS label\n\nFROM personal_data.weekly_micronutrient_summary\nWHERE $__timeFilter(week_start_date) \n  AND  user_id = ${user}\n  AND nutrient_name = 'Potassium (mg)'\nORDER BY week_start_date\n"
    }
   ]
  },
  {
   "title": "Zn - Zinc (mg)",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \n    week_start_date,\n    avg_percent_of_rda || '% (' || weekly_status || ')' AS label\n\nFROM personal_data.weekly_micronutrient_summary\nWHERE $__timeFilter(week_start_date) \n  AND  user_id = ${user}\n  AND nutrient_name = 'Zinc (mg)'\nORDER BY week_start_date\n"
    }
   ]
  },
  {
   "title": "Se - Selenium (mcg)",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \n    week_start_date,\n    avg_percent_of_rda || '% (' || weekly_status || ')' AS label\n\nFROM personal_data.weekly_micronutrient_summary\nWHERE $__timeFilter(week_start_date) \n  AND  user_id = ${user}\n  AND nutrient_name = 'Selenium (mcg)'\nORDER BY week_start_date\n"
    }
   ]
  },
  {
   "title": "Iodine (mcg)",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \n    week_start_date,\n    avg_percent_of_rda || '% (' || weekly_status || ')' AS label\n\nFROM personal_data.weekly_micronutrient_summary\nWHERE $__timeFilter(week_start_date) \n  AND  user_id = ${user}\n  AND nutrient_name = 'Iodine (mcg)'\nORDER BY week_start_date\n"
    }
   ]
  },
  {
   "title": "Cr - Chromium (mcg)",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \n    week_start_date,\n    avg_percent_of_rda || '% (' || weekly_status || ')' AS label\n\nFROM personal_data.weekly_micronutrient_summary\nWHERE $__timeFilter(week_start_date) \n  AND  user_id = ${user}\n  AND user_id = ${user}\n  AND nutrient_name = 'Chromium (mcg)'\nORDER BY week_start_date\n"
    }
   ]
  },
  { "title": "B Vitamins", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 } },
  {
   "title": "B1 - Thiamin (mg)",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \n    week_start_date,\n    avg_percent_of_rda || '% (' || weekly_status || ')' AS label\n\nFROM personal_data.weekly_micronutrient_summary\nWHERE $__timeFilter(week_start_date) \n  AND  user_id = ${user}\n  AND user_id = ${user}\n  AND nutrient_name = 'Thiamin (mg)'\nORDER BY week_start_date\n"
    }
   ]
  },
  {
   "title": "B2 - Riboflavin (mg)",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \n    week_start_date,\n    avg_percent_of_rda || '% (' || weekly_status || ')' AS label\n\nFROM personal_data.weekly_micronutrient_summary\nWHERE $__timeFilter(week_start_date) \n  AND  user_id = ${user}\n  AND nutrient_name = 'Riboflavin (mg)'\nORDER BY week_start_date\n"
    }
   ]
  },
  {
   "title": "B3 - Niacin (mg)",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \n    week_start_date,\n    avg_percent_of_rda || '% (' || weekly_status || ')' AS label\n\nFROM personal_data.weekly_micronutrient_summary\nWHERE $__timeFilter(week_start_date) \n  AND  user_id = ${user}\n  AND nutrient_name = 'Niacin (mg)'\nORDER BY week_start_date\n"
    }
   ]
  },
  {
   "title": "B4 - Choline (mg)",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \n    week_start_date,\n    avg_percent_of_rda || '% (' || weekly_status || ')' AS label\n\nFROM personal_data.weekly_micronutrient_summary\nWHERE $__timeFilter(week_start_date) \n  AND  user_id = ${user}\n    AND nutrient_name = 'Choline (mg)'\nORDER BY week_start_date\n"
    }
   ]
  },
  {
   "title": "B5 - Pantothenic Acid (mg)",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \n    week_start_date,\n    avg_percent_of_rda || '% (' || weekly_status || ')' AS label\n\nFROM personal_data.weekly_micronutrient_summary\nWHERE $__timeFilter(week_start_date) \n  AND user_id = ${user}\n  AND nutrient_name = 'Pantothenic Acid (mg)'\nORDER BY week_start_date\n"
    }
   ]
  },
  {
   "title": "Vitamin B6 (mg)",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \n    week_start_date,\n    avg_percent_of_rda || '% (' || weekly_status || ')' AS label\n\nFROM personal_data.weekly_micronutrient_summary\nWHERE $__timeFilter(week_start_date) \n  AND  user_id = ${user}\n  AND user_id = ${user}\n  AND nutrient_name = 'Vitamin B6 (mg)'\nORDER BY week_start_date\n"
    }
   ]
  },
  {
   "title": "B7 - Biotin (mcg)",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \n    week_start_date,\n    avg_percent_of_rda || '% (' || weekly_status || ')' AS label\n\nFROM personal_data.weekly_micronutrient_summary\nWHERE $__timeFilter(week_start_date) \n  AND user_id = ${user}\n  AND nutrient_name = 'Biotin (mcg)'\nORDER BY week_start_date\n"
    }
   ]
  },
  {
   "title": "B8 - Inositol (mg)",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \n    week_start_date,\n    avg_percent_of_rda || '% (' || weekly_status || ')' AS label\n\nFROM personal_data.weekly_micronutrient_summary\nWHERE $__timeFilter(week_start_date) \n  AND  user_id = ${user}\n  AND nutrient_name = 'Inositol (mg)'\nORDER BY week_start_date\n"
    }
   ]
  },
  {
   "title": "B9 - Folate (mcg)",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 171 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \n    week_start_date,\n    avg_percent_of_rda || '% (' || weekly_status || ')' AS label\n\nFROM personal_data.weekly_micronutrient_summary\nWHERE $__timeFilter(week_start_date) \n  AND user_id = ${user}\n  AND nutrient_name = 'Folate (mcg)'\nORDER BY week_start_date\n"
    }
   ]
  },
  {
   "title": "Vitamin B12 (mcg)",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 179 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \n    week_start_date,\n    avg_percent_of_rda || '% (' || weekly_status || ')' AS label\n\nFROM personal_data.weekly_micronutrient_summary\nWHERE $__timeFilter(week_start_date) \n  AND  user_id = ${user}\n  AND nutrient_name = 'Vitamin B12 (mcg)'\nORDER BY week_start_date\n"
    }
   ]
  }
 ]
}